repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
  - repo: https://github.com/returntocorp/semgrep
    rev: 'v0.41.1'
    hooks:
      - id: semgrep
        # See semgrep.dev/rulesets to select a ruleset and copy its URL
        args: ['--config', 'r/python.flask', '--error']